# Generated by Django 4.0.3 on 2022-04-05 08:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sudoapi', '0002_alter_usermodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
